# This file should be in the root of the repository
# If one of the blocks is not needed, it can be deleted
version: 1
frontend:
  entrypoint:
    index: index.html
    path: /project
env:
  FOO: bar
  BAR: foo
