# This file should be in the root of the repository
# If one of the blocks is not needed, it can be deleted
version: 1
domain_name: ayasite.myvnc.com
frontend:
  entrypoint:
    index: index.html
env:
  FOO: bar
  BAR: foo
