stages:
  - name: build
    image: alpine:3.13
    commands:
      - echo "hello world"

  - name: create-image
    image: nginx:1.25.3-alpine
    commands:
      - mkdir /app
      - cp -r /usr/share/nginx/html /app
    ports:
      - 80
    env:
      - key: foo
        value: bar
      - key: fofo
        value: babar
