# Этот файл должен быть в корне репозитория
# Если один из блоков не нужен, то его можно удалить
version: 1
# Переменные окружения развернутого проекта
app:
  webserver: php
  version: "8.1"
  env:
    FOO: bar
    BAR: foo
  # Путь к проекту и главная страница
  entrypoint:
    index: index.php
