# This file should be in the root of the repository
# If one of the blocks is not needed, it can be deleted
version: 1
# Block of instructions for the build stage
build:
  language: python
  version: 3.9
  strat_commands:
    - pip install -r requirements.txt
    - python3 ./app.py
