# Этот файл должен быть в корне репозитория
# Если один из блоков не нужен, то его можно удалить
version: 1
build:
  image: alpine:3.13
app:
  webserver: nginx
  # Переменные окружения развернутого проекта
  env:
    FOO: bar
    BAR: foo
  # Путь к проекту и главная страница
  entrypoint:
    index: index.html
    path: /var/www/project
