version: 1
entrypoint:
  index: "index.html"
env:
  FOO: bar
  BAR: foo
build:
  commands:
  - echo "hello world"
  - ls -la ./
  - echo "sleepping" && sleep 5
  - echo "3" && sleep 1
  - echo "2" && sleep 1
  - echo "1" && sleep 1
  - echo "BOOM"
