# This file should be in the root of the repository
version: 1
build:
  image: nodejs
  version: 18
  build_commands:
    - npm install --loglevel=verbose
frontend:
  entrypoint:
    index: index.html
env:
  FOO: bar
  BAR: foo
