stages:
  - name: build
    image: alpine:3.13
    copy:
      - echo "hello world"
      - ls -la ./

  - name: create-image
    image: nginx:1.25.3-alpine
    copy:
      - ./ /usr/share/nginx/html
      - ./index.html  /var
    ports:
      - 80
    env:
      - key: foo
        value: bar
      - key: fofo
        value: babar
