versions: 1
env:
  FOO: bar
  BAR: foo
build:
  commands:
  - echo "hello world"
  - ls -la ./
  - echo "sleepping" && sleep 5
  - echo "3" && sleep 1
  - echo "2" && sleep 1
  - echo "1" && sleep 1
  - echo "BOOM"
  image: alpine:3.13
entrypoint:
  index: index.html
  path: /var/www/project
