# This file should be in the root of the repository
# If one of the blocks is not needed, it can be deleted
version: 1
# Block of instructions for the build stage
build:
  image: golang
  version: 1.22.1
    - CGO_ENABLED=0 go build -a -ldflags="-s -w" -o ./app ./
  start_commands:
    - ./app
# Environment variables of the deployed project
env:
  FOO: bar
  BAR: foo
