stages:
  - build
  - deploy

jobs:
  build-image:
    stage: build
    image: "golang:latest"
    script:
      - "go build -o /app/myapp /src/main.go"

  deploy-app:
    stage: deploy
    image: "alpine:latest"
    script:
      - "cp /app/myapp /dist/myapp"
